import Component from "@glimmer/component";
import { tracked } from "@glimmer/tracking";
import { action } from "@ember/object";
import { ajax } from "discourse/lib/ajax";
export default class VipSepayPlans extends Component {
  @tracked busy=false; @tracked message; @tracked name=""; @tracked price=""; @tracked days="30"; @tracked groupId="";
  @action async createPlan(){this.busy=true;try{await ajax("/admin/vip-sepay/plans.json",{type:"POST",data:{plan:{name:this.name,price_vnd:Number(this.price),duration_days:Number(this.days),group_id:Number(this.groupId),active:true}}});this.message="Đã tạo gói VIP.";}catch(e){this.message=e?.jqXHR?.responseJSON?.errors?.join("; ")||"Không thể tạo gói.";}finally{this.busy=false;}}
  <template><div class="vip-sepay-admin"><h1>Gói VIP</h1>{{#if this.message}}<div class="alert alert-info">{{this.message}}</div>{{/if}}<div class="vip-sepay-form-grid"><input placeholder="Tên gói" value={{this.name}} {{on "input" (fn (mut this.name) value="target.value")}} /><input type="number" placeholder="Giá VND" value={{this.price}} {{on "input" (fn (mut this.price) value="target.value")}} /><input type="number" placeholder="Số ngày" value={{this.days}} {{on "input" (fn (mut this.days) value="target.value")}} /><select {{on "change" (fn (mut this.groupId) value="target.value")}}><option value="">Chọn Group</option>{{#each @model.groups as |group|}}<option value={{group.id}}>{{group.name}} ({{group.user_count}})</option>{{/each}}</select><button class="btn btn-primary" type="button" {{on "click" this.createPlan}} disabled={{this.busy}}>Tạo gói</button></div><table class="vip-sepay-table"><thead><tr><th>Tên</th><th>Giá</th><th>Ngày</th><th>Group</th><th>Trạng thái</th></tr></thead><tbody>{{#each @model.plans as |plan|}}<tr><td>{{plan.name}}</td><td>{{plan.price_vnd}} ₫</td><td>{{plan.duration_days}}</td><td>{{plan.group_name}}</td><td>{{if plan.active "Đang bán" "Đã tắt"}}</td></tr>{{/each}}</tbody></table></div></template>
}
